pull_request_rules:
  - name: 🚀 当所有检查通过且审查批准时自动合并
    conditions:
      # 👇 基础分支
      - base=main

      # 👇 所有 Netlify 检查必须成功（或 neutral）
      - "check-success=Netlify: Header rules - goatwiki"
      - "check-success=Netlify: Pages changed - goatwiki"
      - "check-success=Netlify: Redirect rules - goatwiki"
      - "check-success=netlify/goatwiki/deploy-preview"

      # 👇 至少一个批准的审查
      - "#approved-reviews-by>=1"

    actions:
      merge:
        method: merge  # 可选: merge, squash, rebase