name: Auto Merge PR
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled, unlabeled]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}   # ✅ 使用 PAT
          MERGE_LABELS: ""                              # ✅ 不需要标签
          MERGE_METHOD: "merge"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "3000"
          UPDATE_METHOD: "merge"
          MERGE_REQUIRED_APPROVALS: "0"
