name: Enable Auto-Merge for PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-Merge
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
